service: MusicAppServerless

provider:
    name: aws
    runtime: dotnetcore2.1
    region: us-east-2
    role: yourrole

package:
  artifact: bin/Release/netcoreapp2.1/MusicAppServerless.zip
  
functions:
  GetStatus:
    handler: ReleaseMusicServerlessApi::ReleaseMusicServerlessApi.Functions::GetStatus
    description: Get status API
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: /status
          method: get
          cors: true

  CreateUser:
    handler: ReleaseMusicServerlessApi::ReleaseMusicServerlessApi.Functions::CreateUser
    description: Create user
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: /createuser
          method: post
          cors: true

  GenerateTokenUser:
    handler: ReleaseMusicServerlessApi::ReleaseMusicServerlessApi.Functions::GenerateTokenUser
    description: Generate token user
    memorySize: 256
    timeout: 30
    events:
      - http:
          path: /generatetoken
          method: post
          cors: true

  GetMusicReleases:
    handler: ReleaseMusicServerlessApi::ReleaseMusicServerlessApi.Functions::GetMusicReleases
    description: Get music releases
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: /releases
          method: get
          cors: true

  GetMusicsByQuery:
    handler: ReleaseMusicServerlessApi::ReleaseMusicServerlessApi.Functions::GetMusicsByQuery
    description: Get musics by query
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: /listmusics
          method: get
          cors: true

  GetMusicYouTubeEmbed:
    handler: ReleaseMusicServerlessApi::ReleaseMusicServerlessApi.Functions::GetMusicYouTubeEmbed
    description: Get music YouTube embed
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: /youtubemusicid
          method: get
          cors: true